import = ["/home/fatt/.config/alacritty/nord.toml"]

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "D2Coding"
style = "Medium"

[font.italic]
family = "D2Coding"
style = "Italic"

[font.normal]
family = "D2Coding"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Alt"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0017"
key = "Left"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u001BD"
key = "Right"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "PageDown"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Alt"

[[mouse.bindings]]
action = "Copy"
mouse = "Middle"

# [schemes.relaxed.bright]
# black = "0x636363"
# blue = "0x7eaac7"
# cyan = "0xacbbd0"
# green = "0x909d63"
# magenta = "0xb06698"
# red = "0xbc5653"
# white = "0xf7f7f7"
# yellow = "0xebc17a"

# [schemes.relaxed.cursor]
# cursor = "0xd9d9d9"
# text = "0x000000"

# [schemes.relaxed.normal]
# black = "0x151515"
# blue = "0x6a8799"
# cyan = "0xc9dfff"
# green = "0x909d63"
# magenta = "0xb06698"
# red = "0xbc5653"
# white = "0xd9d9d9"
# yellow = "0xebc17a"

# [schemes.relaxed.primary]
# background = "0x353a44"
# foreground = "0xd9d9d9"

[scrolling]
history = 100000

[window]
dynamic_title = true
opacity = 0.8

[window.dimensions]
columns = 125
lines = 25

[window.padding]
x = 4
y = 4
