require("user.options")
-- -- require("user.snip").setup()
require("user.nvim-webdev-icons")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")
require("user.commands")
require("user.colorscheme")
require("user.cmp")
require("user.luasnip")
require("user.lsp")
-- require("user.neotest")
-- require("user.copilot")
-- require("user.supermaven")
require("user.rust-tools")
require("user.telescope")
require("user.treesitter")
require("user.treesitter-context")
require("user.autopairs")
require("user.comment")
require("user.nvim-comment")
require("user.gitsigns")
-- require("user.git-worktree")
require("user.nvim-tree")
-- require("user.oil")
require("user.lualine")
require("user.toggleterm")
require("user.fzf")
require("user.harpoon")
require("user.winbar")
require("user.telescope-vimwiki")
require("user.indent-o-matic")
require("user.mason")
require("user.cellular-automaton")
require("user.cloak")
-- require("user.trouble")
require("user.hurl")
