#!/bin/bash

BAT=$(acpi | grep -E -o '[0-9][0-9][0-9]?%')
BAT_FULL=""
BAT_HALF=""
BAT_LOW=""

# [ ${BAT%?} -ge 80 ] && echo -n "$BAT_FULL  "
# []
# echo "$BAT"

if [ ${BAT%?} -ge 80 ]; then
	echo -n " $BAT_FULL ";
elif [ ${BAT%?} -ge 40 ]; then
	echo -n " $BAT_HALF "
else
	echo -n " $BAT_LOW "
fi

echo "$BAT "
