#!/bin/bash
basedir="/sys/class/backlight/intel_backlight"
max=$(cat "${basedir}/max_brightness")
brightness=$(cat "${basedir}/brightness")

if [ $(( $brightness + 5 )) -lt $max ]; then
	echo $(( $brightness + 5 )) > "${basedir}/brightness"
fi
