# Nord Color Palette

# Polar Night
$polarNight0Alpha  = 2e3440
$polarNight1Alpha  = 3b4252
$polarNight2Alpha  = 434c5e
$polarNight3Alpha  = 4c566a

# Snow Storm
$snowStorm0Alpha   = d8dee9
$snowStorm1Alpha   = e5e9f0
$snowStorm2Alpha   = eceff4

# Frost
$frost0Alpha       = 8fbcbb
$frost1Alpha       = 88c0d0
$frost2Alpha       = 81a1c1
$frost3Alpha       = 5e81ac

# Aurora
$redAlpha          = bf616a
$orangeAlpha       = d08770
$yellowAlpha       = ebcB8b
$greenAlpha        = a3be8c
$purpleAlpha       = b48ead

# Corresponding RGBA values
$polarNight0  = 0xff2e3440
$polarNight1  = 0xff3b4252
$polarNight2  = 0xff434c5e
$polarNight3  = 0xff4c566a

$snowStorm0   = 0xffd8dee9
$snowStorm1   = 0xffe5e9f0
$snowStorm2   = 0xffeceff4

$frost0       = 0xff8fbcbb
$frost1       = 0xff88c0d0
$frost2       = 0xff81a1c1
$frost3       = 0xff5e81ac

$red          = 0xffbf616a
$orange       = 0xffd08770
$yellow       = 0xffebcb8b
$green        = 0xffa3be8c
$purple       = 0xffb48ead

