# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# rules below would make the specific app transparent
#
windowrulev2 = workspace 3, class:^(org.telegram.desktop)$
windowrulev2 = workspace 9, class:^(Slack)$
windowrulev2 = workspace 7, class:^(Postman)$
windowrulev2 = workspace 11, class:^(DBeaver)$
windowrulev2 = workspace 11, class:^(robo3t)$
windowrulev2 = workspace 14, class:^(code-oss)$
windowrulev2 = workspace 8, class:^(Authy Desktop)$

windowrulev2 = opacity 0.8 0.8, class:^(kitty)$
windowrulev2 = opacity 0.8 0.8, class:^(thunar)$
windowrulev2 = opacity 0.8 0.8, class:^(org.telegram.desktop)$
# windowrulev2 = opacity 0.85 0.85, class:^(Slack)$
windowrulev2 = stayfocused, class:(Rofi)
# windowrulev2 = forceinput, class:(Rofi)

windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2 = noblur,class:^(xwaylandvideobridge)$


### Gromit related rules
workspace = special:gromit, gapsin:0, gapsout:0, on-created-empty: gromit-mpx -a
windowrulev2 = noblur, class:^(Gromit-mpx)$
windowrulev2 = opacity 1 override, 1 override, class:^(Gromit-mpx)$
windowrulev2 = noshadow, class:^(Gromit-mpx)$
# windowrulev2 = fakefullscreen, class:^(Gromit-mpx)$
windowrulev2 = size 100% 100%, class:^(Gromit-mpx)$

### terminal related rules
# workspace = special:term, on-created-empty:[float] alacritty

### satty related rules
windowrulev2 = float, class:^(satty)$
