-- -- require("user.winbar").get_winbar()

-- if vim.fn.has("nvim-0.8") == 1 then
-- 	vim.api.nvim_create_autocmd(
-- 		{ "CursorMoved", "CursorHold", "BufWinEnter", "BufFilePost", "InsertEnter", "BufWritePost", "TabClosed" },
-- 		{
-- 			callback = function()
-- 				require("user.winbar").get_winbar()
-- 			end,
-- 		}
-- 	)
-- end
-- -- require("user.winbar")
