#!/usr/bin/env bash

# TODO: get the current rotation state of 'eDP-1'
# TODO: if 0 -> 2
# TODO: if 2 -> 0
TRANSFORM=$(hyprctl monitors -j | jq -r '.[] | select(.name == "eDP-1") | .transform')

case $TRANSFORM in
    0)
        hyprctl keyword monitor eDP-1,preferred,auto,1,transform,2
        hyprctl keyword input:touchdevice:transform 2
        ;;
    *)
        hyprctl keyword monitor eDP-1,preferred,auto,1,transform,0
        hyprctl keyword input:touchdevice:transform 0
        ;;
esac
