#!/usr/bin/env bash
basedir="/sys/class/backlight/amdgpu_bl1"
brightness=$(cat "${basedir}/brightness")

if [ $(( $brightness - 10 )) -gt 0 ]; then
	echo $(( $brightness - 10 )) > "${basedir}/brightness"
fi

