#!/bin/bash
xset s off
prev_status=$(xset q | awk '/abled/ { print $3 }')
# echo "prev status" $prev_status
if [[ $prev_status == "Enabled" ]]
then
    # echo "Disabling dpms"
    xset -dpms
else
    # echo "Enabling dpms"
    xset +dpms
fi

status=$(xset q | awk '/abled/ { print $3 }')
echo $status