#!/bin/bash

jump () {
	mkdir -p $1
	cd $1
}

brg () {
	if [ $2 ]; then
		xrandr --output eDP-1 --output HDMI-1 --brightness $1
	else
		xrandr --output HDMI-1 --brightness $1
	fi
}

dualmon () {
	xrandr --output HDMI-1 --auto --above eDP-1
}

smon () {
	xrandr --output HDMI-1 --off
}

wconn () {
	nmcli d wifi connect $1 password $2
}

test-microphone() {
	arecord -vvv -f dat /dev/null
}

mp3-dl () {
	youtube-dl -x --audio-format mp3 "ytsearch:\"${@}\""

}

keycheck () {
	xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
}
