include ./nord.conf

shell_integration  no-cursor
cursor_shape block

map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/bin/fzf --no-sort --no-mouse --exact -i --tac


# BEGIN_KITTY_THEME
# Nord
# include current-theme.conf
# END_KITTY_THEME

# Select by family only, actual face selection is automatic
font_family family="D2Coding"
# Select an exact face by Postscript name
# font_family postscript_name=D2Coding
# # Select an exact face by family with features and variable weight
# font_family family=SourceCodeVF variable_name=SourceCodeUpright features="+zero cv01=2" wght=380


# include /path/to/your/kitty/nord.conf

# cursor_shape block

env TERM=xterm-256color

font_family D2Coding
font_size 11
bold_font D2Coding Medium
italic_font D2Coding Italic
regular_font D2Coding Regular
adjust_line_height 0
adjust_column_width 0

map kitty_mod+u open_url_with
url_prefixes ipfs ipns magnet mailto gemini gopher https http news file git ssh ftp

map alt+left move_word_left
map alt+right move_word_right
map ctrl+alt+left move_word_left
map ctrl+alt+right move_word_right

map alt+c copy_to_clipboard
map ctrl+shift+c copy_to_clipboard
map alt+v paste_from_clipboard
map ctrl+shift+v paste_from_clipboard

map alt+up increase_font_size
map alt+down decrease_font_size
map alt+shift+plus increase_font_size
map alt+shift+minus decrease_font_size

map page_up scroll_line_up
map page_down scroll_line_down
map alt+page_up scroll_page_up
map alt+page_down scroll_page_down

mouse_bindings:
  - match: button3
    action: paste_from_clipboard

scrollback_lines 100000
dynamic_title yes
background_opacity 0.8
macos_option_as_alt both

initial_window_width 125c
initial_window_height 25c
padding_width 4
padding_height 4

